### PR TITLE
added playlist support

### PR DESCRIPTION
**Pull request by ghost**
This merge request add support to play a list of urls.  
Usage example:
```js
let playlist = [
	'https://ptchan.org/file/10c2b585fc31e5573cc4baecbc96c957b7f0b2f25b710cd3ac8ffbdfeb816cba.mp4',
	'https://ptchan.org/file/6948ec93450ecd5696285193cfefd26143985b26149531a48fe088888147c2c3.webm'
]

let player = new swmp({
	url: playlist[0],
	playlist: playlist
})

let divPlayer = document.querySelector("#player")
divPlayer.appendChild(player.container)
```

What this update do:
- adds a new parameter to the constructor
- adds 2 new functions to go to the next media or previous media
- adds a function to clear the player
	- this will delete the controls and the player container from the html
- adds a function to refresh the player
	- this calls the function to clear the player and handle all yours `prepare` functions  

This update **DO NOT** breaks how your code works, so everything will work the same way as usual, but this time with a new feature added.  

Video example:  
https://files.catbox.moe/sv96g5.mp4  
I'm a retard, so do not merge those stuff without testing your workflow.

### CODE REVIEW

**Comment by ghost** [comment]
Should i also add to `swmp.user.js`?

**Comment by LabMember-001** [comment]
Generally yes, it's the filename for installing userscripts.
I'll start working on some buttons and some other stuff in the meantime.

**Comment by LabMember-001** [comment]
I'm kind of clueless when it comes to git at the moment so there may be a better way to do this (I don't know how to accept your merge into a specific branch only or add commits to your PR myself), but I've added lots of stuff to the playlist support based on the code you gave me (bugfix for multi, minor stylistic changes, styled buttons, playlist location indicator in title, supports adding many types of media to the playlist, ideally the function can be used to make a button that adds all media and youtube files/links on a page into the playlist with the click of a button), I don't want to push to main without having it in my separate branches first so I can more easily see what happened in each update.

I added a branch for this specific update https://github.com/LabMember-001/Simple-Web-Media-Player/tree/patch-11-playlist
If you make the PR to this branch instead I'll merge it there, add my commits, then merge all our commits to main in one go.
Thanks!

**Comment by LabMember-001** [comment]
Nevermind figured it out

**Pull request merged**
